### ISSUE TITLE
Not Assigning IP Addresses

### ISSUE THREAD

**Issue by RoosterGoblin** [NickJongens/ConPineHarvester#1]
Hello! First of all I want to say **thank you** for your hard work in putting together these scripts and publicly releasing them :)

My issue is that I can't get the Pi to properly give out IP addresses! Some of the devices I'm testing will say "Obtaining IP Address Error" and others will just refuse to connect. Setting the network settings/IP address manually on the devices makes everything work as expected, 

I have tried reinstalling everything from scratch along with triple checking my hostapd.conf and ConPineHarvesterStart.sh files, the problem persists :(

Do you have any advice on how I can troubleshoot this issue?

Thanks again!

Edit: just to give some more detail, I'm running kali-linux-2019.3-rpi3-nexmon-64 on a Pi3B+

**Comment by NickJongens** [comment]
Hi RoosterGoblin,

Sorry it took a bit of time to get back to you! I’m using an identical setup :)

Please let me know if you can see if dnsmasq is loading as the DHCP addresses will be handed out via this service.

#check DNSMASQ service.
service dnsmasq status

If this isn’t running, this will definitely be the issue.

I’ll retry the image when I can - busy with work and a baby

Please let me know how you go :)

**Comment by NickJongens** [comment]
Hi John,

I’ve revisited this project and have tested using the code you would have been using.

It has now been resolved and should work for you!
Sorry, I must have been using an old revision stored on my computer.

Cheers
